#!/usr/bin/env python3
"""AMRIT Ad Shield

Safe tools to enable/disable a hosts-based adblocker on macOS / Unix systems.

Usage (review before running):
  # to enable (you will be prompted for sudo by running with sudo):
  sudo python3 workspace/adblocker/ad_shield.py enable

  # to disable (removes AMRIT block and optionally restores backup):
  sudo python3 workspace/adblocker/ad_shield.py disable

The script will also keep backups under workspace/adblocker/backups for safe undo.
"""
from __future__ import annotations
import os
import sys
import shutil
import datetime
import urllib.request
from pathlib import Path
from typing import List

STEvenBLACK_URL = "https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts"
MARKER_START = "# >>> AMRIT-SHIELD START >>>"
MARKER_END = "# <<< AMRIT-SHIELD END <<<"

WORKSPACE = Path(__file__).resolve().parents[1]
BACKUP_DIR = WORKSPACE / "adblocker" / "backups"
BACKUP_DIR.mkdir(parents=True, exist_ok=True)
HOSTS_PATH = Path("/etc/hosts")


def fetch_blocklist(url: str = STEvenBLACK_URL) -> List[str]:
    """Download a hosts-formatted blocklist and return a list of domains.
    We parse lines like: 0.0.0.0 domain.tld or 127.0.0.1 domain
    and return the domains only.
    """
    print(f"Fetching blocklist from: {url}")
    with urllib.request.urlopen(url, timeout=30) as resp:
        raw = resp.read().decode("utf-8", errors="ignore")
    domains = []
    for line in raw.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split()
        if len(parts) >= 2:
            # host entries may have multiple domains after the ip
            for dom in parts[1:]:
                # ignore localnames
                if dom and not dom.startswith("#") and "." in dom:
                    domains.append(dom.lower())
    # dedupe while preserving order
    seen = set()
    out = []
    for d in domains:
        if d not in seen:
            seen.add(d)
            out.append(d)
    print(f"Fetched {len(out)} unique domains")
    return out


def build_marker_block(domains: List[str], target_ip: str = "0.0.0.0") -> str:
    lines = [MARKER_START]
    lines.append(f"# Generated by AMRIT ad_shield at {datetime.datetime.utcnow().isoformat()}Z")
    for d in domains:
        lines.append(f"{target_ip} {d}")
    lines.append(MARKER_END)
    return "\n".join(lines) + "\n"


def backup_hosts() -> Path:
    ts = datetime.datetime.utcnow().strftime("%Y%m%dT%H%M%SZ")
    backup_local = BACKUP_DIR / f"hosts.backup.{ts}"
    # copy from /etc/hosts to backups (requires read perm)
    print(f"Backing up {HOSTS_PATH} to {backup_local}")
    shutil.copy2(HOSTS_PATH, backup_local)
    return backup_local


def remove_existing_block(content: str) -> str:
    # remove any previous AMRIT block between markers
    start = content.find(MARKER_START)
    end = content.find(MARKER_END)
    if start != -1 and end != -1 and end > start:
        before = content[:start]
        after = content[end + len(MARKER_END):]
        return before.rstrip() + "\n\n" + after.lstrip()
    return content


def _read_include_file() -> list:
    inc = WORKSPACE / "adblocker" / "include.txt"
    out = []
    if inc.exists():
        try:
            with inc.open("r", encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if not line or line.startswith("#"):
                        continue
                    out.append(line.lower())
        except Exception:
            pass
    return out


def enable(shield_name: str = "AMRIT-SHIELD", preview: bool = False) -> None:
    """Enable the AMRIT adblock. If preview=True, show the generated block without
    requiring root or writing to /etc/hosts.
    """
    domains = fetch_blocklist()
    # Read any user-provided include list and ensure these hostnames are
    # present and prioritized at the top of the generated block.
    includes = _read_include_file()
    if includes:
        # Normalize includes and dedupe while preserving order
        normalized_includes = []
        seen_includes = set()
        for d in includes:
            dd = d.strip().lower()
            if not dd or dd.startswith("#"):
                continue
            if dd not in seen_includes:
                normalized_includes.append(dd)
                seen_includes.add(dd)
        # Build final domains list: includes first, then fetched domains that aren't in includes
        final = list(normalized_includes)
        for d in domains:
            if d not in seen_includes:
                final.append(d)
        domains = final

    if not domains:
        print("No domains fetched or included; aborting")
        return

    # If preview requested, just print the generated marker block and exit
    if preview:
        block = build_marker_block(domains)
        print("--- AMRIT block preview (first 200 lines) ---")
        for i, line in enumerate(block.splitlines()):
            if i >= 200:
                print("... (truncated)")
                break
            print(line)
        return

    # From here on we perform a write — require root
    if os.geteuid() != 0:
        print("Enable operation requires sudo/root. Run with: sudo python3 workspace/adblocker/ad_shield.py enable")
        sys.exit(2)

    # read existing hosts
    with HOSTS_PATH.open("r", encoding="utf-8") as f:
        orig = f.read()
    # backup
    backup_local = backup_hosts()
    # remove any existing AMRIT block
    newbase = remove_existing_block(orig)
    block = build_marker_block(domains)
    newcontent = newbase.rstrip() + "\n\n" + block
    # write back
    print(f"Writing updated hosts file to {HOSTS_PATH} (this requires root)")
    with HOSTS_PATH.open("w", encoding="utf-8") as f:
        f.write(newcontent)
    print(f"Adblock enabled. Backup saved to: {backup_local}")


def disable(restore_backup: bool = False) -> None:
    if os.geteuid() != 0:
        print("Disable operation requires sudo/root. Run with: sudo python3 workspace/adblocker/ad_shield.py disable")
        sys.exit(2)
    with HOSTS_PATH.open("r", encoding="utf-8") as f:
        content = f.read()
    newcontent = remove_existing_block(content)
    with HOSTS_PATH.open("w", encoding="utf-8") as f:
        f.write(newcontent)
    print("AMRIT block removed from /etc/hosts")
    if restore_backup:
        # find the latest backup in BACKUP_DIR
        backups = sorted(BACKUP_DIR.glob("hosts.backup.*"), reverse=True)
        if backups:
            latest = backups[0]
            print(f"Restoring backup from {latest}")
            shutil.copy2(latest, HOSTS_PATH)
            print("Restoration complete")
        else:
            print("No local backups found to restore")


def verify(domain: str = "doubleclick.net") -> bool:
    # check /etc/hosts contains an entry for domain mapped to 0.0.0.0 or 127.0.0.1
    try:
        with HOSTS_PATH.open("r", encoding="utf-8") as f:
            content = f.read()
    except Exception as e:
        print(f"Failed to read {HOSTS_PATH}: {e}")
        return False
    for line in content.splitlines():
        if domain in line and (line.strip().startswith("0.0.0.0") or line.strip().startswith("127.0.0.1")):
            print(f"{domain} is blocked by hosts entry: {line.strip()}")
            return True
    print(f"{domain} not found as blocked in {HOSTS_PATH}")
    return False


def cli():
    import argparse
    p = argparse.ArgumentParser(description="AMRIT hosts adblocker controller")
    sub = p.add_subparsers(dest="cmd")
    en = sub.add_parser("enable", help="Enable adblock (requires sudo)")
    en.add_argument("--preview", action="store_true", help="Show generated AMRIT block and exit (no changes)")
    sub.add_parser("disable", help="Disable adblock (requires sudo)")
    v = sub.add_parser("verify", help="Verify a domain is blocked")
    v.add_argument("domain", nargs="?", default="doubleclick.net")
    args = p.parse_args()
    if args.cmd == "enable":
        enable(preview=getattr(args, "preview", False))
    elif args.cmd == "disable":
        disable()
    elif args.cmd == "verify":
        ok = verify(args.domain)
        sys.exit(0 if ok else 3)
    else:
        p.print_help()


if __name__ == "__main__":
    cli()
