"""SelfCodeGenerator

Small helper to generate Python modules and simple web bundles and record them
in a KnowledgeBase. This file was copied in and had missing imports; this
update fixes imports, sanitizes names and adds minimal logging.
"""
import os
import re
import time
import logging

import sys
import os as _os
_ROOT = _os.path.dirname(_os.path.dirname(_os.path.dirname(_os.path.abspath(__file__))))
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)

try:
    from knowledge_store import KnowledgeStore as KnowledgeBase
except Exception:
    class KnowledgeBase:  # type: ignore
        """No-op fallback when knowledge_store is unavailable."""
        def add_knowledge(self, *a, **kw): pass


_SAFE_NAME_RE = re.compile(r"[^A-Za-z0-9_.-]")


def _sanitize_name(name: str) -> str:
    """Return a filesystem-safe name derived from `name`."""
    return _SAFE_NAME_RE.sub("_", name)


class SelfCodeGenerator:
    def __init__(self, knowledge_base: KnowledgeBase, out_dir: str = "generated"):
        self.kb = knowledge_base
        self.out_dir = out_dir
        os.makedirs(self.out_dir, exist_ok=True)
        logging.getLogger(__name__).debug("SelfCodeGenerator initialized, out_dir=%s", self.out_dir)

    def generate_python_module(self, module_name: str, code_content: str) -> str:
        module_name_safe = _sanitize_name(module_name)
        filename = f"{module_name_safe}.py"
        path = os.path.join(self.out_dir, filename)
        with open(path, "w", encoding="utf-8") as f:
            f.write("# Auto-generated by SelfCodeGenerator\n")
            f.write("# timestamp: {}\n".format(time.time()))
            f.write(code_content + "\n")
        logging.info("Generated python module: %s", path)
        # store minimal metadata in the knowledge base
        try:
            self.kb.add_knowledge(f"generated:{module_name_safe}", {"path": path, "created": time.time()})
        except Exception:
            logging.debug("KnowledgeBase.add_knowledge failed for %s", path, exc_info=True)
        return path

    def generate_simple_web(self, name: str, html: str, js: str = "", css: str = "") -> str:
        name_safe = _sanitize_name(name)
        base = os.path.join(self.out_dir, name_safe)
        os.makedirs(base, exist_ok=True)
        html_path = os.path.join(base, "index.html")
        with open(html_path, "w", encoding="utf-8") as f:
            f.write("<!-- Generated HTML -->\n" + html)
        if js:
            with open(os.path.join(base, "script.js"), "w", encoding="utf-8") as f:
                f.write(js)
        if css:
            with open(os.path.join(base, "style.css"), "w", encoding="utf-8") as f:
                f.write(css)
        try:
            self.kb.add_knowledge(f"generated:web:{name_safe}", {"path": html_path, "created": time.time()})
        except Exception:
            logging.debug("KnowledgeBase.add_knowledge failed for web bundle %s", html_path, exc_info=True)
        logging.info("Generated web bundle: %s", base)
        return base

